server:
  port: 10042

api:
  version: "1.0.0"

management:
  server:
    port: 9001
  endpoints:
    jmx:
      exposure:
        include: health
    web:
      exposure:
        include: health

logging:
  level:
    ROOT: DEBUG
    com.sboot.micro.example.mvc.resource: INFO
